name: Cypress Test

on:
  push:
    branches:
      - main

jobs:
  cypress:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14  # Adjust to your project's Node.js version

      - name: Install dependencies
        run: npm install cypress

      - name: Run Cypress tests
        run: npx cypress run 
